### ISSUE TITLE
Progressive web app - custom 'touch icon' on homescreen installation

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/best-evidence#100]
As a user that installs the application onto my homescreen (https://github.com/dwyl/best-evidence/issues/37), I want the application to have the BestEvidence logo

- [x] Add the Best Evidence logo to the touch icon for mobile

@Cleop please can you add a time estimate to this?

**Comment by Cleop** [comment]
For Chrome:
https://developers.google.com/web/fundamentals/engage-and-retain/web-app-manifest/#customize_the_icons

**Comment by ajburls** [comment]
@markwilliamfirth  I get an icon for the app on the iPhone but not on the Android (Samsung S7) whether using Chrome or Dolphin to get an app on the home screen. I tried deleting the current icon for the app and then re-adding again just now and it did not renew with logo. Unfortunately since doing that I cannot login from the Android phone it says wrong username/password etc.

**Comment by markwilliamfirth** [comment]
There wasn't time to resolve this bug in sprint 2, so it will move to sprint 3

**Comment by markwilliamfirth** [comment]
Moving this to priority 2 as Amanda mentioned in an email she would like this fixed as a priority

**Comment by SimonLab** [comment]
@ajburls could you try on your android and iphone, I think @Cleop has updated this issue. Let us know if you still can't see the right icon when you add the application on your homescreen, thanks

**Comment by ajburls** [comment]
No icon on Android. Moreover, Android now not looking like an app as it did before (much nicer) but looking like a webpage with wasted space at top with address field  etc. (No logo when save on to home page or in address.)

**Comment by ajburls** [comment]
tested in Chrome and Dolphin in case it made a difference. Would be better to revert to previous version if this can't be solved as preferable to have it look like an app.

**Comment by markwilliamfirth** [comment]
@ajburls as a follow up to our call earlier, please retest this by following these steps:

1. Remove the app from your homescreen
2. Open chrome
3. Click the three vertical dots at the top right to open the menu
4. Select History
5. Clear your history
6. Close Chrome
7. Reopen Chrome
8. Go to Best Evidence app domain
9. Click the three vertical dots at the top right to open the menu
10. Click add to home screen
11. Click Add

The app should appear with the logo, when it is opened there is no search bar / editable URL

Please let me know if this works or doesn't work

**Comment by ajburls** [comment]
Looks great. I noticed a flash screen just before it opened that said "Best Evidence Practice" -it would be good if that could be changed to just "BestEvidence" (also if spaces can be removed from any other occurrence of best evidence e.g. About Best Evidence. Not critical but probably not very time consuming. Looks really nice now.

**Comment by Cleop** [comment]
Phew! Glad we've got it working @ajburls 

Happy to make the change for the copy, however, please can you open this as a new issue? Then you can close this issue.

**Comment by markwilliamfirth** [comment]
Closed in favour of:

https://github.com/dwyl/best-evidence/issues/207
https://github.com/dwyl/best-evidence/issues/208
