### ISSUE TITLE
Search Results Design - Remove the line to the left of the search result

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/best-evidence#103]
As a product owner
I would like the line removed from the left of the search result
So I can have a simple design and use the pyramid to display all visual cues instead

@ajburls I have created this issue based on our discussion from last week - please could you add additional detail and a priority label?

**Comment by SimonLab** [comment]
Without the left line:
![image](https://user-images.githubusercontent.com/6057298/29036582-f1a636a8-7b97-11e7-90db-f5df39e1b48c.png)

Is this ok?

**Comment by markwilliamfirth** [comment]
@ajburls please can you test and close this issue?

**Comment by ajburls** [comment]
Yes, screen looking better each time :-)
