### ISSUE TITLE
Spike: Check publication has an ID

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/best-evidence#104]
@SimonLab please can you check if the TRIP API has a section that has a publication ID? This question arose at our last sprint planning meeting - it relates to understanding whether we can save search notes against a publication for others to see, as well as in user's personal notes sections

**Comment by SimonLab** [comment]
![image](https://user-images.githubusercontent.com/6057298/29046000-82603d04-7bbd-11e7-8f81-f8fda5680ef7.png)
All the documents have a unique id (called also "id" in the API) that we can use to identify a specific element
