### ISSUE TITLE
Database setup

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/best-evidence#12]
Database setup (where will data be stored, how does it need to be retrieved/analysed/formatted)

**Comment by SimonLab** [comment]
phoenix manage database with migrations. We have deployed phoenix now here: http://best-evidence-app.herokuapp.com/.
So now each time we want to update the database we just need to create a new migration.
I think the database details should be linked to the feature, for example for "create login feature" we want to create a table "user" in postgres with the following column: email, password_hash, type

So I think we can close this issue and add more detail when necessary on each issue where we describe a specific feature, @markwilliamfirth @Cleop  what do you think?

**Comment by markwilliamfirth** [comment]
@SimonLab sounds good 👍
