### ISSUE TITLE
Bottom Nav Bar

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/best-evidence#125]
This needs to be created in line with Harry's wireframes #9 

<img width="373" alt="screen shot 2017-08-11 at 14 51 19" src="https://user-images.githubusercontent.com/5732209/29215875-a6d9dd68-7ea4-11e7-8191-977cd410e137.png">

**Requirements:**

- [x] Implementation of UI for bottom nav bar on mobile

- [x] Linking of the bottom nav bar to respective pages

- [x] Include history as a selection

- [x] Sticky bottom nav

- [x] Top on desktop

 - [x] Only shows when logged in
 
- [x] Repositions other pages around navbar spacing

**Comment by markwilliamfirth** [comment]
Include history as a selection

**Comment by ajburls** [comment]
@SimonLab @Cleop Thanks - this looks good and is working.
