### ISSUE TITLE
User Settings: Display User Type Functionality

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/best-evidence#126]
Linked to #24 

As a product owner
I want users to be able to see what user type they picked in their settings
So they can remind themselves of what they chose

**Requirements**

- [x] Display the user type the user selected when they signed up to the application

**Comment by ajburls** [comment]
Working well but still has capital "L" on lay and no "special" or "code" or similar option that I can ask particular people to use

**Comment by SimonLab** [comment]
@ajburls the list has now been updated, let us know if everything is working well :+1:

**Comment by markwilliamfirth** [comment]
@ajburls please can you test and close this issue if you are happy?

**Comment by ajburls** [comment]
@markwilliamfirth Working well, thanks
