### ISSUE TITLE
Simple registration and login for users

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/best-evidence#13]
Simple registration and login for users, to allow us to tie searches to a user ID as well as to set up the required access for sprint 2 features (such as search history review and notes). Does not include user categories (as seen in wireframes) in this issue, these will be added later as a lower priority.

**Sign Up**
- [x]  Users sign up using email and creating 6 char min password
- [x]  Users agree to proceed with sign up (giving consent to sharing data, at this stage this will not be optional)
- [x] Mobile styling - (note: replace the first 'i' symbol removing font awesome)
- [x] Basic desktop styling
- [x] Add tests for the registration/login features

<img src="https://user-images.githubusercontent.com/16775804/28322648-8a9d9c04-6bce-11e7-8985-958cde9382f6.png" width=200px />

<img src="https://user-images.githubusercontent.com/16775804/28322134-3f8f6126-6bcd-11e7-80fc-df7a9c5c48e1.png" width=200px />

**Login**
- [x] Existing users can sign in with email/username
- [x] Mobile styling
- [x] Basic desktop styling

<img src="https://user-images.githubusercontent.com/16775804/28322106-21abea58-6bcd-11e7-87bb-2bc63659f241.png" width=200px />

**Comment by SimonLab** [comment]
@ajburls this issue is now ready to be tested on staging: https://best-evidence-staging.herokuapp.com/
The staging application is where the product owner test and validate the new freshly implemented features. Once you are happy with the feature we will deploy the new changes to the production application (https://best-evidence-app.herokuapp.com/) where the other users can test and **use** the application. This process allow us to be sure that we are not deploying faulty feature in production

**Comment by ajburls** [comment]
@SimonLab Well I went in and created and account and did a search. Second attempt to open just goes to search so I can't test the screen where you login as it doesn't appear. I will test later on a different device.

The search bit is just falling off screen on left and not centred like on the other test page (Where both it and the test results are much prettier - not closely bunched font with link underlined.)

**Comment by SimonLab** [comment]
Thanks for testing @ajburls 
The search view is not yet completed but it is in progress see #15 

It's true that testing the login view after having creating a new user is difficult at this stage as we keep the user always signin. This make me think that we might want to add a logout functionality, this might be also useful when users will use the application on a public computer for example, they might not want to leave their account open. Do you think this is a useful feature?

**Comment by ajburls** [comment]
Thinking about this, I agree with @SimonLab, viz. given that people may use this on public computers e.g. in the hospital library, they will need to be able to logout to maintain the confidentiality and integrity of their account. However, now I know how to delete the cookies for testing purposes I think this functionality can be deferred to Sprint 2. 

Should I be adding this as an issue or is this discussion the issue?

**Comment by SimonLab** [comment]
@ajburls I think you are right, do you mind to create this new issue?
I think we can put a logout button maybe on the setting page?
