### ISSUE TITLE
User Settings: User Type Functionality

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/best-evidence#130]
Linked to #24 

As a product owner
I want users to be able to change their user type in their user settings
So they can keep their account up to date

**Requirements**
- [x] Users can click 'change' in settings to change their user type
- [x] Users select given user type from checkboxes
- [x] Updated user type is saved in the db
- [x] Also appears on sign-up (reveal checkboxes by clicking on heading)

**Comment by markwilliamfirth** [comment]
e.g.
Student
Health Professional
Member of the Public

@ajburls to confirm list of 8 user types

**Comment by markwilliamfirth** [comment]
@ajburls please could you confirm the list of 8 user types?

**Comment by ajburls** [comment]
Doctor
Nurse
Other healthcare professional
Healthcare manager or policy maker 
Academic (e.g. researcher or lecturer)
Undergraduate student
Postgraduate student
Lay member of public (e.g. patient or carer)

(People to be able to select more than one)

**Comment by markwilliamfirth** [comment]
@SimonLab to add "special" user type and change "Lay" to lowercase

**Comment by ajburls** [comment]
Works well. Thanks
