### ISSUE TITLE
About Page - Draft text

### ISSUE THREAD

**Issue by ajburls** [dwyl/best-evidence#132]
Amanda Burls is the Director of ThinkWell and Professor of Public Health at City, University of London. She conceived and designed the BestEvidence app.

Jon Brassey is the Lead for Knowledge Mobilisation at Public Health Wales (NHS) and Director of Trip Database Ltd.  Trip database is the meta-search engine for clinical information used by BestEvidence.

Jose Emparanza is the Head of the Department of Clinical Epidemiology Unit at the University Hospital Donostia, Spain and a founding member of the International Society for Evidence-Based Health Care. He explored the utility and acceptability of BestEvidence for promoting evidence-based practice with clinicians and established that there is a need and demand for this tool.

City, University of London is a world-leading centre for healthcare education and applied healthcare research. City funded the development of BestEvidence in order to facilitate the use of research evidence to inform and improve learning, practice and policy and thereby improve patient outcomes

**Comment by ajburls** [comment]
@Cleop 

Text: ThinkWell Link to: www.ithinkwell.org
Text: Trip Database [second occurrence] Link to: https://www.tripdatabase.com/
Text:  International Society for Evidence-Based Health Care  Link to: http://www.isehc.net/
Text: City, University of London [second occurrence] Link to: https://www.city.ac.uk/

**Comment by ajburls** [comment]
@cleop THanks for adding these
Link to www.iThinkWell.org is not going to the website but returning "page not found" despite fact that website is working.
The link to **City, University of London** is in wrong place it should be on second occurrence of phrase - that is the first occurrence in paragraph 4.

Still awaiting confirmation from City that they are happy with wording.

**Comment by ajburls** [comment]
@Cleop City are happy with wording, but very keen that the corrections to the about us page identified in previous comment are corrected as a first priority before the app is shared with anyone else.

**Comment by SimonLab** [comment]
@ajburls the links should be correct now, let us if this works, thanks.
![image](https://user-images.githubusercontent.com/6057298/29563800-14cccb2e-8737-11e7-98bd-b43b95d3c20c.png)

**Comment by ajburls** [comment]
Thanks @SimonLab , this is great.
