### ISSUE TITLE
Test filter by evidence category

### ISSUE THREAD

**Issue by Cleop** [dwyl/best-evidence#139]
Tests needed for filter by evidence category in the search controller.

**Comment by SimonLab** [comment]
and only add the even listener on the search result page,otherwise javascript will try to get the filter dom element by id and fail as it doesn't exist on the other pages:
![image](https://user-images.githubusercontent.com/6057298/29402643-9f68facc-832d-11e7-9020-eef2c18a36fc.png)

**Comment by SimonLab** [comment]
The tests have been added with #192
