### ISSUE TITLE
Setup access to the TRIP database via API

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/best-evidence#14]
- [x]  @SimonLab @ajburls - to check we have access to the API that we need
- [x]  Setup access to the TRIP database via API

**Comment by ajburls** [comment]
Introduction email sent to Jon Brassey.

**Comment by SimonLab** [comment]
I manage to send some requests using the API with:
```/search/json?key=xxx&criteria=water```
This send back a json reply containing all the list

However I'm not sure yet how the filtering feature works. The filter seems dynamic and depends of the search terms. Also I don't think the API give you any information about the filter so I need to do a bit more tests to understand the logic:
- [ ] understand the different type of filter - write documentation
- [ ] find out if it is possible to get the list of filters with a API requests
- [ ] write down my understanding of the API and @ajburls and Jon will be able to validate it

I'm going to update the time estimation on this issue as there is quiet a bit of research to do to understand how to create more complex API requests with filters. I will

**Comment by SimonLab** [comment]
tripdatabase blog to understand the evidence pyrmid: https://blog.tripdatabase.com/2017/04/20/the-evidence-pyramid/

**Comment by SimonLab** [comment]
I've send an email to Jon to know what is the best way to get the filters data. Otherwise I think we can close this issue: we can send api requests with and receive the json response. The details about how to get the right data for the filters will be discuss in the next issues

**Comment by SimonLab** [comment]
setup with #56
