### ISSUE TITLE
Bug: Tachyons Not Working

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/best-evidence#144]
A new version of tachyons was published yesterday https://unpkg.com/tachyons@4.8.1 https://www.npmjs.com/package/tachyons

This has caused the old Tachyons link to stop working

Proposed solution: use npm to get the new package and check and update the package when necessary

**Comment by SimonLab** [comment]
we were using an external css link to load Tachyons in our project:
https://github.com/dwyl/best-evidence/blob/491bf5e2facfa5ffc70da8786aa066f69f5998b7/web/templates/layout/app.html.eex#L25

with the new version (4.8.1) it appears that the linked is now broken so all of our css was also broken. We could have just updated to the next version with https://unpkg.com/tachyons@4.8.1 but this doesnt' solve the issue on the long term and when a next future version will be released.
The solution is to use the [npm package of Tachyons](https://www.npmjs.com/package/tachyons) and the postinstall script provided by npm to copy the Tachyons css file just downloaded by npm to the right Phoenix folder which contains all the css files: [/web/static/css](https://github.com/dwyl/best-evidence/tree/master/web/static/css)

**Comment by SimonLab** [comment]
resolved with #151 and #150
