### ISSUE TITLE
Allow users to create and save blank notes

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/best-evidence#145]
Linked to https://github.com/dwyl/best-evidence/issues/136

**Comment by ajburls** [comment]
@SimonLab 

Thanks, able to write and save notes and records appearing in history. If the issue about showing that there are notes when paper opened on subsequent searches, is captured somewhere else this issue can be closed. (I think the latter was for the next Sprint?)

**Comment by SimonLab** [comment]
> If the issue about showing that there are notes when paper opened on subsequent searches

@ajburls I'm not sure I understand fully what you mean with this issue. Do you mind to open a new issue for this with some details (and screenshots if possible) and I think you can close the current issue. Thanks
