### ISSUE TITLE
Implementation of online database platform for admin queries

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/best-evidence#146]
As a product owner
I want to be able to query the database
So that I can have a better understanding of what my users are doing

**Acceptance Criteria**

- [x] Implement Redash
- [x] Set up Redash subscription after 30 day trial

This issue is purely for the implementation of the system (Redash requested initially) and not for the solution and data it provides

**Comment by ajburls** [comment]
@markwilliamfirth wasn't someone going to send me a link to ElephantSQL or something similar so that I could try this out?

**Comment by markwilliamfirth** [comment]
@ajburls yes this will happen during the sprint - please move this issue higher in the list if you would like it done before other issues

**Comment by ajburls** [comment]
@markwilliamfirth mark, I think the place for creating the access to the backend database is in the right ranking, but is there something I can be playing with in the interim before you get to this?

**Comment by markwilliamfirth** [comment]
@ajburls 

Here are the links to the suggested two solutions above:
https://www.elephantsql.com/
https://redash.io/

It appears like redash has a demo too:
https://demo.redash.io/

I've contacted ElephantSQL to ask if they have a demo

**Comment by ajburls** [comment]
Thanks

**Comment by markwilliamfirth** [comment]
<img width="463" alt="screen shot 2017-08-30 at 14 40 55" src="https://user-images.githubusercontent.com/5732209/29870637-4185a43c-8d91-11e7-8950-469fd90207be.png">

**Comment by markwilliamfirth** [comment]
From @ajburls via email:

>I don’t really understand these too much (and would prefer to only learn about one in detail) but I notice redash is free and elephantSQL has a monthly charge, so ceteris paribus, I would tend to go for the former. The question is are other things equal?

Amanda has expressed a preference for Redash due to it being free, providing the functionality is sufficient compared with eSQL

**Comment by markwilliamfirth** [comment]
@ajburls i think we should move this one up in priority so that we do it sooner and so you have time to test out the solution prior to the end of the sprint in case we need to make changes - what do you think?

**Comment by ajburls** [comment]
Agreed

**Comment by Cleop** [comment]
@ajburls @markwilliamfirth - ElephantSQL and Redash are somewhat different from a technical perspective. Both do have free offerings but both of those free offerings have limitations. 

From a technical perspective Redash is currently more appropriate for our needs. It gives us access to our live database. In comparison, ElephantSQL is a hosting service (our site is already hosted and therefore this is not needed) and it is via its hosting that you can access your data.

So Redash is more appropriate from a technical perspective. The drawback? Redash's free version only lasts 30 days. For the time being I'm going to look more into Redash. FYI @ajburls Redash's packages start at $29 per month.

**Comment by markwilliamfirth** [comment]
I just spoke to @arikfr (Arik) from Redash - he saw our issue pop up on Redash's mentions and wants to offer us a free account (providing we have reasonable usage) - he's going to comment here 😄

**Comment by arikfr** [comment]
Hi everyone 👋

As @markwilliamfirth mentioned already, I will be happy to provide you with a free account. 

Keep up the good work 👍

**Comment by markwilliamfirth** [comment]
@Cleop once you make the account just ping @arikfr and he can make it free :)

(maybe make it with the best evidence gmail account? Whatever works best!)

**Comment by ajburls** [comment]
This is great news. Thanks to everyone for this 😊

**Comment by Cleop** [comment]
Hey @arikfr! Thank you so much for your kind offer. I've set up an account for us at: best.evidence.dev@gmail.com - please can you set us up on a plan so we can continue using it after the 30 day trial?

**Comment by markwilliamfirth** [comment]
Hey @arikfr! Not sure if you saw this - would you be able to upgrade our Redash account?

**Comment by arikfr** [comment]
Hi,

I set your account as free. Enjoy :)

**Comment by ajburls** [comment]
Thanks everyone :-)

**Comment by ajburls** [comment]
@cleop following on from our discussions about how to keep emails hidden from researchers, I asked Arik this question and he came up with a workaround which I append below. Are you able to implement this?


Hi,

> is it possible to have one field that isn’t visible to me as the database owner, or would this have to be encrypted in the database.

It's something you can manage via your database, by giving the correct permissions to the user you use with Redash (it's possible to scope user's read permissions to specific columns in a table). Also I recommend making sure this user is a read only user (only SELECT access) to make sure scenarios like "accidently wiping the database" doesn't happen.

Best,
Arik.

--
Arik	Arik from Redash
Powered by Intercom
On Tue, Sep 19, 2017 at 07:03 PM, "ajburls" <amanda.burls.1@city.ac.uk> wrote: 
intercom

**Comment by ajburls** [comment]
@markwfirth the redash database is staging database needs to be newly deployed database. Can this be changed? Is this something I can do? Haven't had a reply to previous question re providing access to full database except emails.

**Comment by markwilliamfirth** [comment]
@ajburls - @Cleop will look into this, but since Cleo is booked on another project now it is only something she can do in the mornings/evenings/when she has time so hopefully we'll get this sorted early next week

**Comment by ajburls** [comment]
@markwilliamfirth Thanks Mark. I need the backend to work with the real database so I can monitor how the students are using it and give them feedback etc. (Also to monitor soft launch of the app!)

**Comment by ajburls** [comment]
@markwilliamfirth @arikfr No, this appears to still be the staging database not the new one - screenshot below just taken now showing old dates back to early Sept.

![image](https://user-images.githubusercontent.com/30235568/30810054-ae8b49fa-a1fb-11e7-8aa9-b2b504ec27a0.png)

**Comment by SimonLab** [comment]
I manage to see the current data:
![image](https://user-images.githubusercontent.com/6057298/30810846-3f1a953c-a1fe-11e7-84a1-4168f21190dd.png)
Maybe you might need to refresh some query but I think it should already be done automatically.

**Comment by ajburls** [comment]
OK Working now
