### ISSUE TITLE
Simple TRIP database search

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/best-evidence#15]
Simple TRIP database search ensuring the search is working and displays the number of results as well as all of the required information available through the API (e.g. title and sub-title as per TRIP, level of evidence pyramid)

Linked to #14 

<img src="https://user-images.githubusercontent.com/16775804/28272766-61ab72be-6b04-11e7-9725-e1e5cec6ec94.png" width=250 />
*Note: not including the history section
<img src="https://user-images.githubusercontent.com/16775804/28272864-a7773440-6b04-11e7-98f9-a58c404b8d63.png" width=250px />
*Note: not including the filtering. See #25 for search filtering.

**Comment by Cleop** [comment]
Going to look into how we autofocus the page onto the input bar when loaded so users can type immediately without having to click the input box.
