### ISSUE TITLE
Podcast on Best Evidence Practices

### ISSUE THREAD

**Issue by SimonLab** [dwyl/best-evidence#155]
I found this podcast this weekend:
 http://freakonomics.com/podcast/bad-medicine-part-1-story-rebroadcast/

I think it's worth listening, it explains what are best evidence practices

**Comment by ajburls** [comment]
Thanks @SimonLab , you may be interested in [www.testingtreatments.org](url) where we accumulate resources like this that help lay people understand what makes a fair test of treatment, the most basic aspect of EBP.
