### ISSUE TITLE
Link back to search from notes page

### ISSUE THREAD

**Issue by ajburls** [dwyl/best-evidence#159]
As a user, I would like to go back to search page directly from a note and not have to go via history as at present. (see screenshot).

Is this something that will automatically be put in place with the buttons on the bottom that are being done?( Will these be on every page?)
![image](https://user-images.githubusercontent.com/30235568/29554392-d5c29028-8716-11e7-82a4-aaab4deba514.png)

**Comment by SimonLab** [comment]
On mobile the footer will indeed have the search icon which lead the user to the main search page:
![image](https://user-images.githubusercontent.com/6057298/29563621-52c01c02-8736-11e7-9a11-fbf776ac94c5.png)
On Desktop we will add a link near "history" and this will be on every page I think

**Comment by markwilliamfirth** [comment]
@ajburls please could you test and close this issue if you are happy?

**Comment by ajburls** [comment]
Looks good. Thanks.
