### ISSUE TITLE
Can search results indicate studies previously clicked through to?

### ISSUE THREAD

**Issue by ajburls** [dwyl/best-evidence#163]
As a user, I would like to know which studies I have previously clicked through to look at, by, say, these being shown in a different colour in the returned search results (analogous to the way that links that have been clicked through to on documents etc. change colour).

The titles are sometimes not explanatory and this would reduce re-clicking through to useless studies and also help the user remember studies they found useful and perhaps have already made notes about.

**Comment by ajburls** [comment]
Here I have just re-run a search I did yesterday

![image](https://user-images.githubusercontent.com/30235568/29566807-fb21595e-8742-11e7-9daf-bcbaf70fd5d5.png)


It is not possible to tell from this which papers I have already opened to seek an answer to the question

**Comment by ajburls** [comment]
In contrast I ran a search on TRIP clicked through to two resources which then became paler. I then re-ran the search and these remained paler, indicating that the links had been used.
![image](https://user-images.githubusercontent.com/30235568/29566960-9fbf3e72-8743-11e7-858c-05294f8099d2.png)

**Comment by SimonLab** [comment]
I've clicked on the first three links, would this difference of colour work?
![image](https://user-images.githubusercontent.com/6057298/29584755-a0fbf602-877c-11e7-8281-cd4e271c3616.png)

**Comment by ajburls** [comment]
@SimonLab yes, that is sufficient and I have tested laptop and it works. One side effect is that I now notice that notes that you look at again become paled as well. I am not sure this is helpful but neither is it a huge problem.

**Comment by SimonLab** [comment]
@ajburls the side effect should be resolved now. Let us know if it works for you. Thanks.

**Comment by ajburls** [comment]
@SimonLab Thanks Simon, all resolved so I will close this issue.
