### ISSUE TITLE
Update lazy loading template

### ISSUE THREAD

**Issue by SimonLab** [dwyl/best-evidence#165]
As a user I want to have the same view for the result loaded automatically with lazy loading and I want these papers/publications saved on my history when I click on them so I can have a full and complete history.
![image](https://user-images.githubusercontent.com/6057298/29585222-4a24226c-877e-11e7-9ac5-ee1637463093.png)

- [x] Update the template send to the front end to be the same as the one generated on the backend
- [ ] load existing publications with their notes from the database to determine which of the add or edit icon should be displayed
 - [x] ~~pass cookies with ajax request~~

**Comment by SimonLab** [comment]
Some technical details:
To be able to show the right icon for the publications (add or edit icon), the server needs to get all the publications with their notes for the authenticated user. We can then compare the list of publications from a search to the list of publications already linked to the user. The difficulty of this issue is due to the way we are loading the next page of publication. We are currently using a lazy loading pagination: when a user scroll to the bottom of the search result page a post query is send with javascript from our front-end. However this javascript request doesn't contain the cookie with the id of the user session so our backend is not able to identify the user so it is not possible to get the publication already linked for the specific user.
I've try to reuse the cookie already set by Phoenix for authentication but our current authentication system use ```put_session``` which create a cookie with the HttpOnly flag. This flag doesnt' allow javascript to get the cookie.
We could rewrite our authentication process to use for example JWT bu this implies a bit of work and at this stage I prefer letting Phoenix defining the session.
Another solution that I want to try is to use Phoenix Channels (sockets). Instead of doing ajax requests we might be able to simplify how we load publications with channels.

**Comment by SimonLab** [comment]
The PR #174 is now using Channel instead of ajax. This allow us to identify the user clicking on evidences. This allow us then to know if this particular user has already added a note on one of the publication which is shown on the result page, so we can then decide which icon, edit or add, to display on the page

**Comment by SimonLab** [comment]
Websocket error 103 on Heroku:
![image](https://user-images.githubusercontent.com/6057298/29874616-3f1030b6-8d8f-11e7-9b22-f3e13d153c1e.png)

**Comment by SimonLab** [comment]
![image](https://user-images.githubusercontent.com/6057298/29876553-0c28eb74-8d95-11e7-99bf-6c5e640171b2.png)

**Comment by SimonLab** [comment]
@ajburls on this issue I resolve the display of the icons (add or edit) on the search page (issue also described in #162). Could you test it on your side and let us know if everything is working properly? if yes you can then close this issue.
Thanks

**Comment by ajburls** [comment]
@SimonLab Simon, I don't think is quite working properly. I did a search and then when the search results showed, I wrote a note on the first paper, but the note showed up as a note about the search not about the paper on the notes page (but correctly on the history page. Not sure if this is something to resolve here or will naturally be resolved when the problem about the notes page only showing notes on searches and not notes on papers problem is fixed (Not sure which issue captured in).

**Comment by SimonLab** [comment]
It's true it can be confusing if a note already exists on a search term. If you do a new fresh search and add a note an a publication you should see the edit icon on the publication and the add icon on the search on the history page.
Agree that when the same search terms will be linked (issue #162 ) it will be more obvious that a note has been added to an evidence/publication.
I think this issue can be close, but I let you decide :+1:

**Comment by ajburls** [comment]
@SimonLab Nice job. Thanks!
