### ISSUE TITLE
Public computer checkbox triggers cookies to not work

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/best-evidence#179]
Linked to https://github.com/dwyl/best-evidence/issues/61

- [ ] "This is a public computer" tick box on the login page, ticked by default, triggers cookies to not work

@SimonLab please can you time estimate this?

**Comment by Cleop** [comment]
To clarify by 'triggers cookies not to work' you mean that a user is logged out if the browser is closed? @markwilliamfirth

**Comment by ajburls** [comment]
@Cleop Yes, that is what I meant. If opened on a public machine the person will have to log in each time.

**Comment by markwilliamfirth** [comment]
@ajburls a note to say that this is not a typical user journey / pattern and that typically users would expect a log out button ( #61 ). We would advise this as a more common solution to solve the problem. As we understand privacy of notes is an important issue here and so we would advise to complete issue 61 over this one. Please let us know how you'd like to proceed

**Comment by ajburls** [comment]
@markwilliamfirth I would prefer log out but was trying to find faster solutions to ensure that everything needed was in place by end of Sprint 3. So if there isn't a big differential in time, let's do that. (Currently remembering of login not working anyway so at moment just an academic question.)

**Comment by markwilliamfirth** [comment]
@ajburls I imagine this might take at least the same time, if not more to implement it. So with this in mind we'll proceed with #61 

Is the functionality described here still desired for a later sprint or is the requirement in #61 satisfactory? If the former we'll keep this issue open and please reassign a priority label, if the latter we'll close it.

Linked requirement from 61 mentioned above:
> Include message on login page under 'please log in', "If you are using this app on a public computer, please remember to logout of the app [on the settings page] when you have finished."

**Comment by ajburls** [comment]
#61 enough

**Comment by markwilliamfirth** [comment]
Closed as no longer required
