### ISSUE TITLE
Sharing of Notes by Email

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/best-evidence#18]
Addition of simple share icon on articles which do not currently share content but rather tracks the number of times people click on this to infer whether sharing content is a requirement (this is dependent on how we get the data back from the TRIP database)

**Comment by markwilliamfirth** [comment]
@ajburls would you be able to add a priority label to this issue please?

**Comment by markwilliamfirth** [comment]
Amanda has confirmed email notes: https://github.com/dwyl/best-evidence/issues/8#issuecomment-320298765

**Comment by ajburls** [comment]
@markwilliamfirth I am not sure I understand what this is about.

**Comment by markwilliamfirth** [comment]
@ajburls the above is a note on this issue to confirm that you would like notes to be able to be shared by email. In terms of next steps for this issue, I just need you to assign a priority label to it so we know how to prioritise it in this sprint

**Comment by markwilliamfirth** [comment]
@ajburls do you want a template with the note linked in the email when the note is shared (in a similar way to the feedback button, but without automatic sending - the user chooses who it is sent to)?

**Comment by ajburls** [comment]
@markwilliamfirth Yes

The share button from a search/question needs to produce an email with the search terms used and the content of the free text note any trigger questions (currently only one: did you find evidence to answer your uncertainty? (or words to that effect)) and option selected (Currently: Yes|Partially|No|Not applicable). This should be editable so sender can change content. Perhaps the subject field should say something like: Note from BestEvidence app OR Note about [search terms]

The share button from a paper  needs to produce an email with the search terms used and the content of the free text note any trigger questions of which there are several and display the option selected for each. If no answer selected this should be visible. This also should be editable so sender can change content. Perhaps the subject field should say something like: Note about [brief name of paper]

User would enter email address like feedback button.

**Comment by markwilliamfirth** [comment]
## Requirements:

In both instances the user would enter the email address to share

**Sharing a search note:**

- [ ] Email created

- [ ] Subject of email is _Note about [search terms]_

- [ ] Email body:

  - [ ] Search terms used

  - [ ] Content of the free text note

  - [ ] Trigger question _Did you find evidence to answer your uncertainty?_

  - [ ] Option selected _Yes|Partially|No|Not applicable_

  - [ ] Email body should be editable before sending

**Sharing a publication note:**

- [ ] Email created

- [ ] Subject of email is _Note about [name of paper]_

- [ ] Email body:

  - [ ] Search terms used

  - [ ] Content of the free text note

  - [ ] Trigger question _Did you find evidence to answer your uncertainty?_

  - [ ] Option selected _Yes|Partially|No|Not applicable_

  - [ ] Email body should be editable before sending

@ajburls can you confirm the above requirements are correct?

**Comment by ajburls** [comment]
@markwilliamfirth 

Almost :-)
The sharing a publication note would be the note trigger questions (see #31)

What is the design of this paper?
[Drop down list from which only one can be selected]
• Guideline
• Policy document
• Systematic Review
• Randomized controlled trial
• Cohort study
• Case-control study
• Qualitative study
• Economic evaluation
• Diagnostic test accuracy study
• Cross-sectional study/Survey
• Clinical prediction rule
• Other
[perhaps free text box for people to specify what it was if they choose "other"?]

Validity - how trustworthy did you find this resource?
High | Moderate | Unclear | Low

Results - what were the key findings?
[free text box]

Relevance - are the results generalizable to your context?
Yes | Somewhat | Unclear | No

Did the findings influence your decision?
Select one of the following
• Not applicable
• Yes – it changed what I would have done
• Yes – it helped confirm what I would have done
• No

**Comment by markwilliamfirth** [comment]
Times estimate is for original design questions

New trigger questions are not part of this sprint https://github.com/dwyl/best-evidence/issues/31

**Comment by SimonLab** [comment]
@ajburls this is ready to be tested. You should see an email icon on the top right of the edit page of notes:

![image](https://user-images.githubusercontent.com/6057298/30066769-cb0e2738-9250-11e7-8a52-f41ff55fffaf.png)

**Comment by ajburls** [comment]
Yes working fine.

**Comment by ajburls** [comment]
Can't test on iPhone as out of better but close as working well on android
