### ISSUE TITLE
New bottom menu bar obscures save button on notes 

### ISSUE THREAD

**Issue by ajburls** [dwyl/best-evidence#186]
Can no longer save a note without closing keyboard on notes page since implementation of menu at bottom of screen
<img src="https://user-images.githubusercontent.com/30235568/29956599-06908dba-8ee0-11e7-8342-fd4bcd0ca125.png" width=200px />

- [x] Remove extra line of text at the top 'Create Note' etc.
This alone is unlikely to be enough space created.
- [x] Hide the bottom navbar at this height
- [x] Put the search term inline with the 'search term:' words

**Comment by ajburls** [comment]
![screenshot_20170901-062551](https://user-images.githubusercontent.com/30235568/29956599-06908dba-8ee0-11e7-8342-fd4bcd0ca125.png)

**Comment by markwilliamfirth** [comment]
@ajburls we could resolve this by making the notes box smaller - would you be happy with this?

**Comment by ajburls** [comment]
Yes this would be ok but i think it would be better to remove dead space at top by, for example having it titled: New note for search: [search terms]

This would get rid of need for line with word "search"

Or if new red warning, which is scheduled to be moved above box,  were to fit on line after "make a note"

**Comment by SimonLab** [comment]
We might have a look also on how to fix the footer navigation bar like this the keyboard might avoid bringing up the navigation which will let show the save button without having to reduce the other element

**Comment by ajburls** [comment]
@SimonLab  I don't know exactly what "this" is but this sounds like a good solution

**Comment by Cleop** [comment]
I've made the following changes so far:
- Remove extra line of text at the top 'Create Note' etc.
- Hide the bottom navbar when keyboard is up
- Put the search term inline with the 'search term:' words

I've tested this using my iPhone 5 and Simon's android phone and it works. You do have to scroll from the top of the page but you can see the 'save note' button from the top of the text box when you have your keyboard open. However we'll have to see if this is still the case when there is the 'note complete' checkbox and the 'Validity etc.' reminder there too. If this continues to be an issue I think we will have to resize the text box.

This is not yet merged in, @ajburls I will assign you and change the label once it is ready to test.

**Comment by ajburls** [comment]
@cleop I can now save notes by scrolling to save on both my android and iphone without closing keyboard.
