### ISSUE TITLE
Bug: Internal Server Error Related to Note Text Limit

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/best-evidence#187]
This issue relates to the bug that Amanda mentioned in the stand up today

An internal server error occurs when a user tries to save a note with a lot of text

Currently unknown what the cause is, however this may be related to a text limit on the database

**Comment by SimonLab** [comment]
Linked to the type of the column. Need to check how to define a type text with Ecto
![image](https://user-images.githubusercontent.com/6057298/29964898-8c54cd1c-8f03-11e7-9908-24862f1eef1e.png)

**Comment by SimonLab** [comment]
@ajburls This should be fixed now. Could you try to create a note with a long description, if everything is ok you can then close this issue, thanks

**Comment by ajburls** [comment]
@SimonLab Looks good. Thanks.
