### ISSUE TITLE
Basic Google Analytics

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/best-evidence#19]
Implementation of Google Analytics at a basic level to track page views

- [x]  Add GA script to track page views for individual pages
- [x]  Create filter so that traffic to staging does not impact production site's data
- [x]  Set up tag manager

**Comment by Cleop** [comment]
I've set up the basic scripts for Tag Manager and Analytics which I will then test once they've been merged in.

**Comment by Cleop** [comment]
Closing as tested and all criteria complete
