### ISSUE TITLE
Drop down menu for type of study returning internal server error

### ISSUE THREAD

**Issue by ajburls** [dwyl/best-evidence#191]
Drop down menu for type of study returning internal server error so can't select by study type

**Comment by SimonLab** [comment]
It might be the same issue spotted by @joseempa #175  , I will check that the fix hasn't been removed. Thanks for spotting that @ajburls

**Comment by SimonLab** [comment]
As the search controller as changed to include the notes linked to the publication we need to do the same when a filter is applied. This was linked to #165 (not #175)

**Comment by SimonLab** [comment]
This should be fix now @ajburls , let us know if it works for you, thanks

**Comment by ajburls** [comment]
Working again. Thanks.
