### ISSUE TITLE
Change icons - add, edit, complete

### ISSUE THREAD

**Issue by SimonLab** [dwyl/best-evidence#197]
The icons have been changed on the history page to represent if a note is complete or not:
![image](https://user-images.githubusercontent.com/6057298/30025555-f7bc9688-9170-11e7-824e-9226b7704840.png)

We now need to change the icons on the search, note and result page.

**Comment by SimonLab** [comment]
The icons should be the correct ones on all the pages now. @ajburls this is ready to be tested, thanks.

**Comment by ajburls** [comment]
@SimonLab Looks good. Thanks
