### ISSUE TITLE
voice recognition api?

### ISSUE THREAD

**Issue by SimonLab** [dwyl/best-evidence#2]
Which one is the best?
- https://cloud.google.com/speech/ ?
- https://www.houndify.com/
	              Free	Small	Medium	Large	Enterprise
Monthly Price	$0	$99	$249	$749	Contact Us
Included Credits	100/day	500/day	2,000/day	10,000/day	Custom

- using the browser:
  - https://developer.mozilla.org/en-US/docs/Web/API/Web_Speech_API/Using_the_Web_Speech_API
  - api, https://www.labnol.org/software/add-speech-recognition-to-website/19989/

Credits per query are calculated based on the following formula:
For text queries: 0.25 + domain credits
For audio queries: 0.25 * seconds of audio + domain credits

Other links:
- https://pypi.python.org/pypi/SpeechRecognition

**Comment by SimonLab** [comment]
So I have now a better view:

w3c provide a webSpeechApi which can be use directly from the browser. However it doesn't seem yet implemented on Safari (mobile and desktop). This would be the easy/quicker way to implement voice recognition if the compatibility wasn't an issue. It seems also that each browser would use their own system to convert audio to text which might give different result depending on the browser
- https://developer.mozilla.org/en-US/docs/Web/API/Web_Speech_API#Browser_compatibility
- http://stackoverflow.com/questions/32517331/different-between-google-speech-api-and-web-speech-api

Another option is to use an external API. This looks a bit more complicated to implement (but doable) and it should work on every devices. However most of the api are not free so we might need to see what would be the cost on a long term use

- https://cloud.google.com/speech/
- https://www.houndify.com/

**Comment by SimonLab** [comment]
This article looks nice, I'm going to use it to try to record audio from the browser before sending it to houndify or google speech api

**Comment by markwilliamfirth** [comment]
@SimonLab ok to close?

**Comment by markwilliamfirth** [comment]
@iteles where should this research be recorded? (assume it needs to be recorded like https://github.com/dwyl/best-evidence/issues/3)

**Comment by markwilliamfirth** [comment]
Closing in favour of https://github.com/dwyl/hq/issues/380
