### ISSUE TITLE
Admin Functionality

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/best-evidence#20]
Amanda's account will have access to a page called 'admin' which can be accessed from her settings page.

At its most basic, the page will be a table with 2 columns, the first will be an anonymised user id, the second will be a list of searches made.

Potential additions: date of search, articles clicked, notes made for search, notes made for publications. The time estimates will need to be made for these separately as they will change the scope of the issue.

**Comment by markwilliamfirth** [comment]
@ajburls this issue was generated from the original proposal - can you confirm if this is still a high priority and edit the priority label as appropriate?

**Comment by ajburls** [comment]
@markwilliamfirth Confirmed that this is a high priority as it is integral to us being able to undertake research about how the app is used.

**Comment by markwilliamfirth** [comment]
@ajburls thank you for confirming this - please could you clarify how you would like this to be implemented?

The current assumption is the following (based on the original scope):

- There will only be one administrator login
- The administrator will be able to login through a different admin page (not within the app login)
- There will be two columns (1) User ID (2) Search

Please can you confirm if there are any additions to this? I would perhaps recommend another column for the timestamp the search was made.

**Comment by ajburls** [comment]
@markwilliamfirth For the MVP a single admin log in to view the backend would be sufficient. (Ideally, we would like to have more admin access to the database with different levels of permissions, so, for example the College of Optometry users data only could be observed by the College of Optometry researcher, or some people can view and analyse but only a few can clean and edit data.) Yes, this should not be within the app but completely separate functionality. I am sure that the analysis would be done on a computer as a large screen would be needed.

I don't really understand why you have assumed there would be only two columns. (I have been assuming it provides access to the backend database.)

Yes we would want an anonymised user ID but one would also need access to to a column with search, date of search, articles clicked through to, notes made about search, notes made about question. I think this would simply reflect the already extant (and being developed) back-end database that is currently populating the app when used for each user.  

It would be lovely if there were some automated analytics e.g. number of searches made in last day/week/month/year/all time. Or proportion of registered users that have used app in last day/week/ etc. Or average number of searches/user or average number of papers clicked through to per search. Number of searches with notes, number of searches with completed notes, number and or proportion of papers clicked through to with notes, number of completed notes for same etc. 

I had assumed that the admin person would have to do all this work themselves and that there would be search functionality like any database (e.g. where you could filter by different data e.g. date of search or single user ID) but maybe to do this would require exporting the data? Can new queries be made given the way the database is currently designed.

**Comment by markwilliamfirth** [comment]
@ajburls some of this has already been mentioned at our stand up catch ups, but thought it's best to summarise here:

>I don't really understand why you have assumed there would be only two columns. (I have been assuming it provides access to the backend database.)

The only reason for this is that this was the requirement from the original scope, it's completely fine if the scope has changed, we just need to keep in mind the priorities for the project so we deliver everything that's required by the close of sprint 3.

**Summary of MVP requirements:**

- [ ] Single admin

- [ ] Not within the app, separate functionality

- [ ] anonymised user ID

- [ ] Columns with (@ajburls has noted what she is looking for may be similar to @SimonLab 's view of the database):

  - [ ] search
  - [ ] date of search
  - [ ] articles clicked through to
  - [ ] notes made about search
  - [ ] notes made about question

- [ ] Automated analytics (linked to #19 #26)
  - [ ] Number of searches made in last day/week/month/year/all time
  - [ ] Proportion of registered users that have used app in last day/week/month/year/all time
  - [ ] Average number of searches per user
  - [ ] Average number of papers clicked through to per search
  - [ ] Number of searches with notes
  - [ ] Number of searches with completed notes
  - [ ] Number of papers clicked through to with incomplete notes
  - [ ] Proportion of papers clicked through to with incomplete notes
  - [ ] Number of papers clicked through to with completed notes
  - [ ] Proportion of papers clicked through to with completed notes
- [ ] Database search functionality (e.g. filter by different data such as date of search or single user ID) (@SimonLab does this require exporting the data? Can new queries be made given the way the database is currently designed?)

**Comment by ajburls** [comment]
@markwilliamfirth agree with above

**Comment by markwilliamfirth** [comment]
Some of the most important functionality desired mentioned in this issue is covered by https://github.com/dwyl/best-evidence/issues/146

Reducing priority to 3 as agreed the rest is not for sprint 3

**Comment by ajburls** [comment]
@markwilliamfirth Mark I am not sure how this issue relates to #146 which is in Sprint 3. Wasn't this a way of doing what is talked about here?

**Comment by markwilliamfirth** [comment]
@ajburls issue 146 is implementation of access to an online database that will allow you to query the database - this is the last bullet point in the above comment (https://github.com/dwyl/best-evidence/issues/20#issuecomment-322217150) and was confirmed to be the most important functionality to be completed this sprint. Can you confirm this?

This issue also links to #26 (analytics)

**Comment by ajburls** [comment]
@markwilliamfirth Yes, confirmed.

**Comment by markwilliamfirth** [comment]
Closing this issue in favour of:

https://github.com/dwyl/best-evidence/issues/26#issuecomment-326266156
https://github.com/dwyl/best-evidence/issues/146
