### ISSUE TITLE
Copy changes: Removing spaces between Best Evidence

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/best-evidence#207]
https://github.com/dwyl/best-evidence/issues/100#issuecomment-327167348

Remove spaces from occurrences of best evidence e.g. About Best Evidence

change to BestEvidence

@ajburls please could you assign a priority label and indicate whether this must be done this sprint?

**Comment by ajburls** [comment]
Priority 4. Would be good to do on this Sprint if poss. As it sets branding for app

**Comment by SimonLab** [comment]
@ajburls I think it is done now @ajburls , let us know if you still spot some wrong name in the application

**Comment by ajburls** [comment]
Looks good. Will close and open new issue if I spot problem
