### ISSUE TITLE
Bug on notes page

### ISSUE THREAD

**Issue by ajburls** [dwyl/best-evidence#212]
Notes page: some searches don't have '+' button to write note
'+' button works fine on history page.

**Comment by ajburls** [comment]
![Uploading IMG_0621.PNG…]()

**Comment by SimonLab** [comment]
@ajburls just to confirm, I think this issue only appears on iphone, it this the case or do you have it also on desktop and android?

**Comment by SimonLab** [comment]
@ajburls I don't think this is a bug, maybe a misunderstanding.
On the note page we only display:
- the search terms where a note has been created and linked to it
- the publications/evidences where a note has been created

The difficulty is to find a way to show the publications/evidences with notes where the search term used for these publications doesn't have a note yet, see my previous question and your answer here:
https://github.com/dwyl/best-evidence/issues/22#issuecomment-326729545

We could add the "+" icon will bean almost the same as the history page? Do we then want to display also all the search term event the ones where the publications linked to it don't have any notes?

**Comment by ajburls** [comment]
Only iphone

**Comment by markwilliamfirth** [comment]
@ajburls just wanted to check you've seen Simon's comment? https://github.com/dwyl/best-evidence/issues/212#issuecomment-327477829

**Comment by ajburls** [comment]
Yes, all looking good.
