### ISSUE TITLE
Bug: Duplicate search original date being used

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/best-evidence#215]
Duplicate search showing on date first searched as opposed to updated search date

e.g. dengue fever was searched yesterday and again today, but still shows as yesterday

<img width="576" alt="screen shot 2017-09-07 at 09 28 02" src="https://user-images.githubusercontent.com/5732209/30153525-de775d6c-93ae-11e7-87f7-10e619107a69.png">

@SimonLab mentioned that this may be that the field currently looks at the 'created' date not the 'updated' date.

**Comment by ajburls** [comment]
Just checked. Appears to be ok.
