### ISSUE TITLE
upgrade limit seach term

### ISSUE THREAD

**Issue by SimonLab** [dwyl/best-evidence#232]
![image](https://user-images.githubusercontent.com/6057298/30731787-576e2642-9f67-11e7-8b5e-97acec1bf763.png)

The term has a type of varchar(255) in the database. We want to upgrade this limit to allow user to search for long term

**Comment by SimonLab** [comment]
@ajburls I just created a fix and it is in review. I think you should still be able to do some searches with some shorter search term, is this right? At this stage I don't want to reset the database as I don't know when your users will be testing the application, however I will be deploying the new fix as it is very quick and shoudn't impact the use of the application. This PR #233  should fix this issue

**Comment by SimonLab** [comment]
@ajburls the new version has been deployed. I would recommend to not search for too long search terms, this issue is fixed on our side however Tripdatabase returns an error if the search term is too long.

**Comment by ajburls** [comment]
Thanks. No need to reset database.

**Comment by markwilliamfirth** [comment]
@ajburls please can you close this issue if this is now fixed on staging?

**Comment by ajburls** [comment]
@SimonLab @markwilliamfirth Yes, thanks, it appears fixed.
