### ISSUE TITLE
Tripdatabase returns an error when search too long

### ISSUE THREAD

**Issue by SimonLab** [dwyl/best-evidence#234]
![image](https://user-images.githubusercontent.com/6057298/30736529-0d16fab0-9f7b-11e7-9051-95cd1d0af3fc.png)

If the search term is too long the Tripdatabase returns an error which will stop the application.

We can catch this error and return an empty search instead

**Comment by SimonLab** [comment]
This is ready to be tested @ajburls . If you do a seacrch with a term too long the application will catch the error returned by Tripdatabase and will return an empty search.

let us know also for the other "please-test" issue if everything works fine. The staging application should be up to date. Once you are happy I can deploy the last changes to production :+1:

**Comment by ajburls** [comment]
Just had a chance to check this (did this on bestevidence.info not sure if this is right) but got internal server error

**Comment by SimonLab** [comment]
@ajburls I haven't deployed yet on bestevidence.info (production) as I didn't want to disturb your demo yesterday. However it should be fixed on staging. If it works correctly let me know and I will deploy on production

**Comment by ajburls** [comment]
@markwilliamfirth @SimonLab This seems to be all in order. Thanks :-)
