### ISSUE TITLE
Delay in updating database

### ISSUE THREAD

**Issue by ajburls** [dwyl/best-evidence#236]
As a researcher, I need to know what searches are being done quite quickly but searches done earlier today are not showing up in the redash backend queries, even though I have refreshed screen. How long should this take?

**Comment by SimonLab** [comment]
@ajburls you can refresh manually the data by clicking on the right top icon:
![redash-refresh-data](https://user-images.githubusercontent.com/6057298/30816120-f116a92a-a20c-11e7-8482-e7df0389ef9a.png)

 I think it might also be possible to define a time on when to refresh the data automatically on the Redash configuration but I'm not sure.

**Comment by markwilliamfirth** [comment]
@ajburls there is also a chat feature in the bottom right corner of the desktop app, that looks like this:
<img width="77" alt="screen shot 2017-09-25 at 16 17 31" src="https://user-images.githubusercontent.com/5732209/30816171-0fde66fe-a20d-11e7-949e-51b3e4e80c64.png">
So Arik might be able to help you if something is not working with Redash as you would expect

**Comment by ajburls** [comment]
@SimonLab Thanks for fast response - sorted :-)

@markwilliamfirth great tip thanks for that - I need to learn how to write new queries so I may be needing this.
