### ISSUE TITLE
User Settings: Create User Settings Page

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/best-evidence#24]
User Settings

As a product owner
I would like a user settings page (designed below)
So that users can have a page where they will (functionality depending) be able to change their speciality, email address and password

This page will be accessed by the cog on the bottom bar shown in Harry's wireframes #9 #125

<img width="373" alt="screen shot 2017-08-11 at 14 51 19" src="https://user-images.githubusercontent.com/5732209/29215859-96f5d852-7ea4-11e7-9a8d-ab69e06823ac.png">

<img width="350" alt="screen shot 2017-08-10 at 17 09 13" src="https://user-images.githubusercontent.com/5732209/29180139-bd2e1c98-7dee-11e7-85be-e2c283f20fb1.png">

**Comment by markwilliamfirth** [comment]
@ajburls this issue was created from the original proposal and is still in the backlog. Please could you update the priority label? For now, I'm adding this to the Sprint 3 planning draft, as I think this is one that should be tackled in Sprint 3.

**Comment by ajburls** [comment]
@markwilliamfirth done - happy for this to go to next sprint

**Comment by markwilliamfirth** [comment]
@Cleop please could you time estimate this?

**Comment by markwilliamfirth** [comment]
I've caught up with Simon and Cleo - this is quite a large issue and we'll need to break it down further.

@ajburls I just wanted to double check with you that you still want all of this functionality as a priority? #126 #127 #128 #129 #130 ? They are all currently in the Sprint 3 draft with priority 3 labels.

**Comment by ajburls** [comment]
@markwilliamfirth I have made two priority 4 to rank these better

**Comment by joseempa** [comment]
I think we could use BMJ Clinical Evidence conditions or categories (32) to help users to explain their interests. They could chooes one or more of these conditions.  We could call them Health Interest Areas, and these are:

1.	Blood and lymph disorders 
2.	Care of the elderly
3.	Child health
4.	Cardiovascular disorders
5.	Diabetes
6.	Digestive system disorders
7.	Endocrine and metabolic disorders
8.	Ear, nose, + throat disorders
9.	Eye disorders
10.	HIV and AIDS
11.	Infectious diseases
12.	Kidney disorders
13.	Lifestyle
14.	Mental health
15.	Musculoskeletal disorders
16.	Men's health
17.	Neurological disorders
18.	Oncology
19.	Oral health
20.	Pregnancy and childbirth
21.	Perioperative care
22.	Poisoning
23.	Respiratory disorders (acute)
24.	Respiratory disorders (chronic)
25.	Social and community health
26.	Sexual health
27.	Skin disorders
28.	Sleep disorders
29.	Supportive and palliative care
30.	Travel health
31.	Wounds
32.	Women's health

**Comment by markwilliamfirth** [comment]
Linked to #143

**Comment by Cleop** [comment]
@markwilliamfirth - the settings page has now been created, can this issue be closed? #126 and #130 are in sprint 3 but #127 #128 and #129 are not. If this issue is meant to be an epic for all of these issues it should be moved out of this sprint because those issues are not scheduled to be completed in this sprint.

**Comment by markwilliamfirth** [comment]
@Cleop yes this can be closed - this issue is just for the creation of the page
