### ISSUE TITLE
Filtering of Searches: Evidence Type & Triangle rating

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/best-evidence#25]
Filtering of searches as per TRIP categorisation

- [x]  Evidence Type by pop up menu
- [x]  Triangle rating

<img src="https://user-images.githubusercontent.com/16775804/28272918-cb3fdda0-6b04-11e7-8e4b-1076cca3d28c.png" width=250px />

Linked to #133 #134

**Comment by SimonLab** [comment]
These are the filters we need to display on the mobile view:
![image](https://user-images.githubusercontent.com/6057298/28273408-38c5e800-6b06-11e7-968f-1e7ca7252b27.png)
The main two important are "secondary evidence" and "guidelines"
@harrygfox do you have an idea on how to display this list nicely on the application?

**Comment by ajburls** [comment]
Personally, I think it would be nice if the sub-menus could be closed and open on clicking if this is not too technically challenging.

**Comment by harrygfox** [comment]
@SimonLab as it is in your screenshot

**Comment by markwilliamfirth** [comment]
Amanda has requested to start on this issue with filtering of evidence type (without submenus). Note that the colour coding of the submenus is important. (T4h)

**Comment by markwilliamfirth** [comment]
Linked to #111

**Comment by markwilliamfirth** [comment]
@ajburls please can you test and close this issue if you are happy?

**Comment by ajburls** [comment]
@markwilliamfirth I think that all the outstanding issues have been captured as other issues so this can be closed
