### ISSUE TITLE
Do GitHub Training with Amanda

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/best-evidence#27]
As a scrum master for the best evidence project
I need our product owner to be an effective and confident user of GitHub
So that we can work in an effective team to complete the best evidence project on GitHub

- [x] Get Amanda signed up to GitHub

- [x] Show Amanda GitHub functionality

**Comment by ajburls** [comment]
OK I have had first meeting with you

**Comment by markwilliamfirth** [comment]
Relates to #17

**Comment by markwilliamfirth** [comment]
This was completed
