### ISSUE TITLE
How to record microphone on Safari (Desktop and iOS)?

### ISSUE THREAD

**Issue by SimonLab** [dwyl/best-evidence#3]
# Context
web app that allow user to search research papers by terms by querying a medical specific domain api. For example the search "Is water good for me?" will return a list of articles linked to the question.
The search is already working and the app can return a list of results see https://best-evidence.herokuapp.com/

# Problem that we are trying to solve:
The users (doctors) will want to be able to search by voice:
- 1 The user click on a "record button" to ask a question
- 2 The voice is converted to text (using google speech api or a similar tool)
- 3 The question text is display on the input search
- 4 The user can correct any errors (some very specific medical terms might not have been converted to text properly) before clicking on the "search button".

The main problem is to know how to record the voice from the microphone on all type of devices.
One way to do this is to use the api [getUserMedia()](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia) which is provided by the WebRTC specification. This will work in most cases but not on Safari (desktop and mobile) **which is a main issue as the users are mostly using apple devices**
- mobile
![getusermediamobile](https://cloud.githubusercontent.com/assets/6057298/25486435/19cdfa06-2b59-11e7-956b-b7cd679a22fa.png)
- desktop
![getusermediadesktop](https://cloud.githubusercontent.com/assets/6057298/25486434/19c6a3b4-2b59-11e7-91f5-a7aaca263e4d.png)

Unfortunately I haven't find a solution (and don't think there is one yet) to record a voice directly from the microphone on Safari iOS. This let me think that we might need to create a specific iOS application (on desktop and for Safari I consider that the users won't mind to type their questions, need to be confirmed).

@nelsonic @iteles @harrygfox do you have any thoughts or any other solutions to allow voice to text on Safari?

see also #2 to so my first ideas

**Comment by markwilliamfirth** [comment]
@SimonLab ok to close?

**Comment by iteles** [comment]
@markwilliamfirth This research needs to be recorded in our documentation before we close

**Comment by markwilliamfirth** [comment]
@iteles where should it be recorded? Should I create a new repo?

**Comment by markwilliamfirth** [comment]
Closing in favour of https://github.com/dwyl/hq/issues/380
