### ISSUE TITLE
Lazy Loading

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/best-evidence#32]
Only load search results when they are required

**Comment by SimonLab** [comment]
- [ ] Create an event listener which detect when a user has scrolled to the bottom of the page
- [ ] Send a post request to our sever to get the next page ex: /search with the payload containing the term searched and the page number
- [ ] Our server send a request to get the next result: ```?criteria=term&skip=20``` the skip query parameter let us drop the n first results
- [ ] Our server format the response and create the html result next list
- [ ] Our front end javscript receive the html response, append to the result list and run again the functions which save the click on a publications

**Comment by markwilliamfirth** [comment]
@ajburls please could you assign a priority label to this issue?

**Comment by SimonLab** [comment]
The lazy loading is ready to be tested on the staging, thanks

**Comment by ajburls** [comment]
Nice :-)
