### ISSUE TITLE
Simple Loading Cap

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/best-evidence#33]
At first only load the first 25 - 30 search results

Later #32

**Comment by markwilliamfirth** [comment]
Linked to #15

**Comment by Cleop** [comment]
The API returns 20 results by default. I recall us mentioning 20 results as a fair number. Are you happy with this @ajburls and @markwilliamfirth? 

To amend this default would be particularly fast and doesn't seem to be a high priority given that 20 is not a great difference.

**Comment by ajburls** [comment]
@Cleop @markwilliamfirth - For the app when finished we need people to be able to scroll through and get to all results if they want to. (This was behind discussion of lazy loading). We said limit to 25 to 30 results for the first development stage to keep app fast during development. 

I would not be happy with 20 as final return on search. 

If you want to limit to 20 during development then that is OK by me

Also if you want to limit to 20 for first returned results in final app, while further results are loading in the background, that is OK too (but users will need to be able to scroll through more results to get to something relevant).

**Comment by ajburls** [comment]
@markwilliamfirth @Cleop 
The final app needs to allow people to view all results if they want to. (This was what led to the discussions about paging results or lazy loading.)

We agreed to limit to 25 to 30 in this sprint to simplify development and speed response of app. I am happy to limit to 20 for this purpose.

I would not be happy to limit to 20 at end of Sprint 2. 

I would be happy to for immediate download of final app to be 20, while rest is loading in background, but at the end of the day users may need to be able to scroll through all results to find something relevant to them.

**Comment by Cleop** [comment]
Great, thanks for the feedback @ajburls. I should have been more explicit. So the 20 default is for the first page, people will be able to view as many resources as the search returns once we implement pagination. We can discuss whether pagination or lazy loading is what we opt for in sprint  2 when it comes to sprint planning. Then we can discuss in more detail the difference between them for both users and in terms of technical implementation time (Relates #16 #32).

So for the purpose of this issue which is about how many results display on first impression after a search is made (as opposed to with lazy loading or with pagination which will come later), there's no opposition to 20 being the number of resources shown (as opposed to 25-30)?

**Comment by ajburls** [comment]
No objection @Cleop

**Comment by Cleop** [comment]
Closing this issue as 25-30 limit no longer needs imposing. Other ways of viewing multiple sources covered in #16 and #32.
