### ISSUE TITLE
 View of recent searches

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/best-evidence#34]
Linked to #35 

<img src="https://user-images.githubusercontent.com/5732209/28275659-7ac95466-6b0c-11e7-9858-0869087b9eb7.png" width=280px />

**Comment by SimonLab** [comment]
- [ ]  create new table "searches" - search_term, count_results, user_id, timestamp
- [ ] change the form to post request as we are now saving data in the database from a search
- [ ] change the search new action to save the search in the database
- [ ] change the search index action to get the list of recent searches, how many do we want to display?

**Comment by Cleop** [comment]
@ajburls - how many 'recent searches' would you like to be displayed? is the last 5 searches enough (as shown in the wireframe so users don't have to scroll when the keyboard is showing)? or would you like more than this?

**Comment by ajburls** [comment]
@Cleop I think that the last 5 would be OK since they are all in the history if people want to go back. If there were more would these be below keyboard rather than displacing keyboard? @joseempa what do you think?

**Comment by ajburls** [comment]
This is working but it has a bug in that if you press "done" from the search page it duplicates the item in the search history. (Does this need to be entered as a separate issue?)

Also we were going to be able to click on the recent searches so that they appeared again in the search box so that they could be edited if refinement was needed. That functionality is not yet there.

**Comment by SimonLab** [comment]
Thanks for testing @ajburls I will have a look at the duplicates item.
The "clicking on recent search" feature is currently in review and should be deployed soon

**Comment by SimonLab** [comment]
@ajburls could you test this view, I think it should be ok now

**Comment by ajburls** [comment]
Looks good.
