### ISSUE TITLE
Save search history data (not with UI)

### ISSUE THREAD

**Issue by Cleop** [dwyl/best-evidence#35]
Functionality without UI:

- [x] Save the search terms data
- [x] Save the publication clicks data

**Comment by SimonLab** [comment]
steps to save publication clicks:
- [ ] create new migration: table publication_history with a foreign key to the search table
- [ ] update the search table to have "has_many" publications
- [ ] update the view "list publication" to add a class
- [ ] create a new route (with json pipe) ```/publications/create``` which will send the url link + the id search as a post request
- [ ] create js script to add event listener for each publication links: For each click send the data to the new endpoint + open a new tab to see the link

**Comment by Cleop** [comment]
Closing as was merged in #72
