### ISSUE TITLE
Progressive web app - install to home screen

### ISSUE THREAD

**Issue by SimonLab** [dwyl/best-evidence#37]
As a developer I need to have a spike on progressive web app and especially the "install on home screen" feature in order to decide what are the technical blockers.

**Comment by Cleop** [comment]
https://www.howtogeek.com/196087/how-to-add-websites-to-the-home-screen-on-any-smartphone-or-tablet/

**Comment by markwilliamfirth** [comment]
This issue has been completed, closing in favour of a new issue derived from this, which is here: https://github.com/dwyl/best-evidence/issues/100
