### ISSUE TITLE
Please invite Dr Jose Emparanza 

### ISSUE THREAD

**Issue by ajburls** [dwyl/best-evidence#38]
As a co-product owner
Dr Jose Emparanza (github ID: joseempa) needs to be invited to the BesetEvidence Github
So he can add issues directly himself

**Comment by markwilliamfirth** [comment]
@joseempa I've sent you an invitation!

**Comment by SimonLab** [comment]
welcome @joseempa . We give an introduction to @ajburls yesterday on how to use Github with this project. I think your main contribution will be to create issues to give feedback and ideas on existing and new features. Maybe the best place for you to start quickly with Github is to read our contributing guide: https://github.com/dwyl/contributing, this should take around 20mn to read this documentation.
Please let us know if you have any questions.
Maybe a first exercise for you is once to confirm with a comment on this issue that you can access the repository and then close this issue if you are satisfied  with it :+1:

**Comment by joseempa** [comment]
Thank you for the invitation.
Questions? Hundreds-thousands... Just arrived. Give me a break to deal with all the new things I see here. That's a fully new way of collaborate !
