### ISSUE TITLE
add dwylbot to the repo

### ISSUE THREAD

**Issue by SimonLab** [dwyl/best-evidence#40]
As a developer I want dwylbot to help me following the contributing guide so I create clear issues

**Comment by SimonLab** [comment]
@iteles I don't think I have the right to add dwylbot to dwyl repositories, do you mind to plug it?
I think if you follow the install instruction guide of dwylbot https://github.com/dwyl/dwylbot#install you should be able to do this. Let me know if you have any blockers :+1:

**Comment by markwilliamfirth** [comment]
@SimonLab I've added dwylbot 👍

**Comment by SimonLab** [comment]
![image](https://user-images.githubusercontent.com/6057298/28315801-fa61167c-6bb7-11e7-8a3c-67c22db3525a.png)
Thanks @markwilliamfirth 
This will push me to fix some bugs on dwylbot too :wink:
