### ISSUE TITLE
Transfer Heroku App

### ISSUE THREAD

**Issue by SimonLab** [dwyl/best-evidence#43]
We have at the moment an heroku app that I have created during my spike "voice recognition" #2 #3 
This application is currently hosted on my dwyl account so we need to transfer it to the new heroku account so that any users with the credentials can access the application configuration

**Comment by SimonLab** [comment]
The new application is now hosted here: https://best-evidence-app.herokuapp.com

**Comment by Cleop** [comment]
Closing as tested 👍
