### ISSUE TITLE
Setup continous integration with Travis + pre-commit

### ISSUE THREAD

**Issue by SimonLab** [dwyl/best-evidence#45]
As a developer I want to be sure that my tests are passing before any push to Github and I want to know when my tests are failing before deploying as I want to be sure that my code is working properly

- [x]  Set up travis
- [x]  Set up pre-commit
- [x]  Add the Travis badge to the readme
- [x] Add codecov badge to the readme

**Comment by Cleop** [comment]
Closing as merged in #47 and a technical issue.
