### ISSUE TITLE
Create staging heroku site

### ISSUE THREAD

**Issue by Cleop** [dwyl/best-evidence#49]
Currently the site has one live version hosted on heroku: https://best-evidence-app.herokuapp.com/
We need to create a second 'staging' version of the site on heroku. The existing version would be known as the 'production' version. 

The reason for doing this is to enable the team to share new features with @ajburls without them going live to people who may be testing the app. This way we have the ability to share progress and to get feedback on this but to get approval before it is seen by testers.

This also safeguards us against any bugs or features that may break the site when deployed, meaning that we can intercept these problems at staging without impacting upon the production site.

The process once a staging site has been created is:
- The team creates new features which are deployed to staging
- @ajburls validates/ tests the features and approves them to go live to the production site
- The new features are deployed on the production site and can be tested by everyone

- [x] Create staging site on heroku
- [x] Set up appropriate measures for autodeployment onto staging

**Comment by SimonLab** [comment]
The staging area is now accessible here: https://best-evidence-stagging.herokuapp.com/
