### ISSUE TITLE
Enter Login Details as Infrequently as Possible

### ISSUE THREAD

**Issue by harrygfox** [dwyl/best-evidence#5]
As a user 
I want to use the app without logging in
So that I don't waste time (on my rounds / in the ward)

This feature is of paramount importance to the users according to Amanda and Jose.

## How might we achieve this?

**Comment by markwilliamfirth** [comment]
We've noted this requirement and agreed with Amanda that logging in once on a web app and the device remembering the login information is sufficient

**Comment by markwilliamfirth** [comment]
Closing this issue as the current setup is adequate - improvements to this are being tracked and actioned from #88
