### ISSUE TITLE
add favicon.ico file to the application

### ISSUE THREAD

**Issue by SimonLab** [dwyl/best-evidence#52]
![image](https://user-images.githubusercontent.com/6057298/28384732-a1345558-6cbd-11e7-9088-4487cb08e8ac.png)

As a user I want to see the logo of best evidence on my tab so that I can recognise quickly the tab of the application

As a developer I want to add a favicon to avoid noise in my logs (get request error for favicon.ico

I think this issue is also linked to #36

**Comment by ajburls** [comment]
![icon](https://user-images.githubusercontent.com/30235568/28385353-b97a889c-6cbf-11e7-986e-05dbf1ec5cd8.png)
![splash](https://user-images.githubusercontent.com/30235568/28385367-c32f9530-6cbf-11e7-9d4e-9fa70c532edf.png)

@SimonLab These are two files of the icon we designed before for the BestEvidence app if this is what you are wanting. (Not sure what is meant by favicon.)  Clearly this would have to be made much smaller for the tab. Let me know if you meant something else. Also, not sure how one tells if the files uploaded properly.

**Comment by ajburls** [comment]
Other smaller versions
![drawable-ldpi-icon](https://user-images.githubusercontent.com/30235568/28385613-b3758cc0-6cc0-11e7-9eb5-f3ebc9db9358.png)
![drawable-mdpi-icon](https://user-images.githubusercontent.com/30235568/28385619-b5d6a666-6cc0-11e7-97b1-4d420b2feebf.png)
![drawable-xhdpi-icon](https://user-images.githubusercontent.com/30235568/28385624-b785615a-6cc0-11e7-9599-9695c57f683d.png)

**Comment by SimonLab** [comment]
Thanks for the files @ajburls :+1: 
the favicon is indeed the small icon displayed on the tab on the left side of the title.
Uploading images on the issues make it easy for us to use them, so yes it's the good way to upload them, thanks.

We will add this icon and we can test if it looks good with the new design

**Comment by ajburls** [comment]
@SimonLab The icon is too small to be visible. It needs to be enlarged even if this means that the ends of the capsule are not visible (or pub with a, say, red background to that it stands out more.

**Comment by Cleop** [comment]
@ajburls Thanks for the feedback. Have a look at the versions below and let me know what you think, ignore the black borders, that's just the background of the page that I've copied the screenshot from.
This is the red option:
<img src="https://user-images.githubusercontent.com/16775804/28525217-64597412-707b-11e7-86a5-39d30df6e978.png" width=18px />
This is a version that has the ends slightly cut off, I didn't cut any further as I didn't want to lose the dots on either end.
<img src="https://user-images.githubusercontent.com/16775804/28525333-c521eac2-707b-11e7-9614-08b6ed1918ff.png" width=18px />

**Comment by ajburls** [comment]
Think red background helps icon to stand out but wonder whether it is good icon. Diagonal would maximise size of capsule.

**Comment by markwilliamfirth** [comment]
![favicon](https://user-images.githubusercontent.com/5732209/28563176-0757d9a0-711d-11e7-8c4d-46bdb29c4047.png)

![favicon-red](https://user-images.githubusercontent.com/5732209/28563227-3d811a82-711d-11e7-859d-a98cfed4b28e.png)

@ajburls what do you think of these two draft designs?

**Comment by ajburls** [comment]
They are good and I think it will help that the image is larger. At this size no background one is more attractive to me. Not sure which would be best on tool bar/tab.

**Comment by Cleop** [comment]
Thanks for the feedback @ajburls - I'll implement no background for now and share once I'm done

**Comment by markwilliamfirth** [comment]
@ajburls please can you test and close this issue if you are happy?
