### ISSUE TITLE
Add pointer when hover on buttons

### ISSUE THREAD

**Issue by SimonLab** [dwyl/best-evidence#57]
As a user I want my cursor to change to a pointer when I hover the buttons on the login and registration page (on desktop) as I want to know which elements are clickable.

- [x] Add pointer when hover on buttons

**Comment by ajburls** [comment]
This working well on desktop version as far as I have tested

**Comment by Cleop** [comment]
Thanks for testing, please close the issue if you are satisfied with testing 👍
