### ISSUE TITLE
Style flash message info and error

### ISSUE THREAD

**Issue by SimonLab** [dwyl/best-evidence#58]
As a user I want to see clearly if any info or error messages are display on the page so that I can see quickly which action I need to take next:

![image](https://user-images.githubusercontent.com/6057298/28424820-8691c128-6d66-11e7-88d6-5459246eea6b.png)

@Cleop @ajburls  we might need to think where we want to display these messages

- [x] Move the error message to display next to the input field on login for existing users
- [x] Info flash message 'Welcome back!' when relogging in
- [x] Oops something went wrong on new sign up
- [x] Add title 'Login' or 'Create an Account' on the respective pages to avoid confusion for users who try to create an account and then are auto-redirected to the login page but who may not realise this has happened. Relates #92

**Comment by markwilliamfirth** [comment]
Amanda has confirmed to move text error near to the submission fields

**Comment by markwilliamfirth** [comment]
Moving this issue to the Sprint 2 milestone, as the feedback for this was not received during Sprint 1

**Comment by markwilliamfirth** [comment]
@ajburls please can you test and close this issue if you are happy?
