### ISSUE TITLE
Need to be able to log out

### ISSUE THREAD

**Issue by ajburls** [dwyl/best-evidence#61]
As a user, I might want to access my BestEvidence account on public computers e.g. in the hospital library

Therefore l need to be able to logout when I have finished 

So that no-one else can see or add to my notes  and maintain the confidentiality and integrity of my account.

**Comment by markwilliamfirth** [comment]
@SimonLab please could you time estimate this?

**Comment by markwilliamfirth** [comment]
@ajburls I've caught up with Simon and we need to know where exactly you'd like the log out button to be and on what pages you'd like it to be on? Would this appear on all pages or perhaps just the user settings page? Please bear in mind that this button will take up a lot of space (especially on mobile) and this needs to be taken into consideration. The simplest and quickest implementation of this functionality would be one logout link/button on the user settings page.

**Comment by ajburls** [comment]
@SimonLab @markwilliamfirth I think that it will be the exception for people to use it on a public computer so the logout button would be OK on the Settings page. Although I think we need to give a clear warning somewhere (login page seems obvious choice) along the lines that 

**If you are using this app on a public computer, please remember to logout of the app [on the settings page] when you have finished.**

So that people are alerted to the fact that just closing the app is not sufficient to prevent others from seeing their account.

**Comment by markwilliamfirth** [comment]
@ajburls great thanks for confirming that - I think this is a good starting point to implement this functionality and can always be further improved upon later

Summary of requirements:

- [ ] Logout button on User Settings Page #24 

- [ ] Include message on login page, "If you are using this app on a public computer, please remember to logout of the app [on the settings page] when you have finished."

**Comment by ajburls** [comment]
@SimonLab @markwilliamfirth Thinking about this today when I was prioritising the changes for Sprint 3, I think it would actually be better to have a tick box on the login page that was ticked by default that said this is a public computer. And the cookies for remembering the login (which still need to be made to work) would not be used when ticked. This would mean that people do not have to remember to log out. This may also be less programming time?

**Comment by markwilliamfirth** [comment]
@ajburls I have added the above feature as a new issue here: https://github.com/dwyl/best-evidence/issues/61

**Comment by markwilliamfirth** [comment]
@ajburls has confirmed to proceed with this

**Comment by ajburls** [comment]
Working. Thanks.
