### ISSUE TITLE
History Notifications

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/best-evidence#62]
As a developer
I would like to have more clarity on how notifications should work from the product owner @ajburls 
So I can build the application correctly

![image](https://user-images.githubusercontent.com/5732209/28463463-65f516ba-6e18-11e7-9494-aef978fdb341.png)

1. What does the dot mean?
Current assumption: it means new notifications are available to be read and it will only appear when this is the case

2. What counts as a new notification?
Current assumption: a search, viewing a source

3. What does the number in brackets refer to?
Current assumption: this is the number of unread notifications

**Comment by ajburls** [comment]
@markwilliamfirth Mark, these aren't notifications as I understand the term notifications (i.e. the app sending new information to the user). This is marking a link showing what you have done in the past. It differs from list shown on search page in that it also documents the links you clicked through to. This is the picture from invision wireframes that @harrygfox  made showing what you would click through to

![image](https://user-images.githubusercontent.com/30235568/28464930-002b89ac-6e1f-11e7-978b-c1ddb4119a77.png)

1. No, it will appear all the time but first time it will show (0)
2. it is always there
3. was presumably the number of items in the history. (on thinking about this now, I see no reason why it needs to give a number)

On subsequent discussion, with Harry I believe, we agreed that there would be note icons on that page where you could write or edit notes, and also could tell if they had a note or not.

Hope this clarifies

We want to add push notifications later but this wasn't in current MVP.

**Comment by markwilliamfirth** [comment]
Thank you @ajburls so to summarise - we will remove the the number next to History

**Comment by markwilliamfirth** [comment]
With regards to the number next to Review All- this is referring to the number of clicks to sources from searches that require review from the doctor? The doctor either leaves a review as to whether their question was answered or not by that source or they skip the review. Wither of these actions decrease the counter - is that correct @ajburls ?

**Comment by ajburls** [comment]
@markwilliamfirth Just to confirm in writing what I said in hangout - I am not totally sure what this meant but it would be helpful for people to know how many searches they had done, or resources they had clicked through to where they had not put a comment so they can review later.

We spoke about writing a note or selecting from a choice (e.g. Yes, this answered my question) would remove reminder for that search/resource. On reflection I don't think this would be the best model as someone might make a short note but still want to review. So a simple check box for each source/resource on the note page where people can switch off if no further review required might be better. (Or switch on "review completed")

**Comment by markwilliamfirth** [comment]
@harrygfox would you be able to clarify further what the original intention of the red dot and number next to the "Review All" means?

**Comment by harrygfox** [comment]
The red dot indicates that there are historical searches that have been made and/or papers that have been read which have not been reviewed. The number (2) indicates that there are either:
- 2 historical searches which have not been reviewed
- 2 papers read which have not been reviewed
- 1 historical search and 1 paper read - neither of which have been reviewed. 

The user reviews each search and paper individually to:
- make a note for that search / paper
- do nothing by tapping `skip`

**Comment by markwilliamfirth** [comment]
@harrygfox thanks for confirming the original design implementation

@ajburls can I confirm you would you like to continue with the decision to remove the review all functionality (as discussed in our sprint planning yesterday)?

**Comment by ajburls** [comment]
I think that we just want a link to history and no flag or numbers but on history users WILL be able to see which questions and papers clicked through to have no notes, which have some notes, which have completed notes.

**Comment by markwilliamfirth** [comment]
@ajburls just to let you know I'm reopening this issue as we need to keep this open until the functionality has been built and tested 👍

**Comment by markwilliamfirth** [comment]
Linked to #71

**Comment by markwilliamfirth** [comment]
Reorganising this by closing this issue in favour of #71 and #122
