### ISSUE TITLE
Reduce space around 'Start Searching' button to avoid need to scroll

### ISSUE THREAD

**Issue by Cleop** [dwyl/best-evidence#63]
**As a** user
**I want to** avoid scrolling to view page content
**So that** I can access the information I need effortlessly and quickly.

Currently the 'Start Searching' button on the login page for existing users is not fully visible on an iPhone 5. To remove the need for scrolling for users, we can reduce the spacing around the button.

Here's how it will now look on iPhone 5:
<img src="https://user-images.githubusercontent.com/16775804/28466198-8f486a34-6e23-11e7-9715-c2224909668c.png" width=250px />

**Comment by ajburls** [comment]
This looks good
