### ISSUE TITLE
Bypass of consent 

### ISSUE THREAD

**Issue by ajburls** [dwyl/best-evidence#69]
As product owner and researcher
I need users to be aware and consent their data is visible on backend if they use app
To meet ethics requirements

Currently a new user going to app for first time can press login on home screen (consent button requires scrolling and could be missed). On login page they can select a new account and set up new account without consenting

**Comment by ajburls** [comment]
@SimonLab  Have been thinking about best way around this and think that home page should remove
![image](https://user-images.githubusercontent.com/30235568/28524812-ed03a79e-7079-11e7-80e8-f9b921607bde.png)

and simply be one screen with login or "Create a BestEvidence Account" link.

That link should go to page with the information about informed consent. And that is only way to get through to screen for creating a profile. All other links to create an account should link to that page.

I prefer the following text for the informed consent page, 
![image](https://user-images.githubusercontent.com/30235568/28525979-edd53828-707d-11e7-86ff-3b2a2188f033.png)

@joseempa  Do you agree with this suggested re-wording and do you have any suggestions to improve it?

**Comment by SimonLab** [comment]
Thanks for spotting this issue @ajburls :+1: I think this new user flow should work

**Comment by Cleop** [comment]
Changes have been made and currently will require a bit of scrolling on iPhone 5: 
<img src="https://user-images.githubusercontent.com/16775804/28568551-2674e48e-712e-11e7-94eb-0eaa0ce3e46b.png" width=300px />
However, we can discuss whether reducing the wording of the button or elsewhere may overcome this if it's a priority.

**Comment by ajburls** [comment]
I have tested this and cannot now get around requirement to login. 

However the text on new informed consent page has typos that need correcting. (Improve the it; reasearch)

Since you will be editing it I think the text could be shortened to:

_All searches and notes are stored in a secure online database. These are accessible, in an anonymised format, to administrators and may be analyzed to understand to help improve the app._

**Comment by ajburls** [comment]
Happy to reduce button wording to

_I agree_

and wording preceding it to

_To agree to this and create an account click button below_

 make it fit on phone

**Comment by SimonLab** [comment]
@ajburls The text has been updated and is ready to be tested, thanks

**Comment by ajburls** [comment]
@SimonLab Looks good. The last paragraph reads oddly, probably because I edited it to change it from patient's to patients' and I think it needs to be changed to 

_Remember not to write any notes that could breach a patient's confidentiality or allow them to be identified._

Otherwise I think this issue can be closed

**Comment by ajburls** [comment]
@SimonLab Not sure if I am supposed to be reviewing this or not but last paragraph still odd and needs changing to

Remember not to write any notes that could breach a patient's confidentiality or allow them to be identified.

Otherwise I think this issue can be closed

**Comment by markwilliamfirth** [comment]
@ajburls please can you test and close this issue if you are happy?
