### ISSUE TITLE
Feedback banner and email address

### ISSUE THREAD

**Issue by harrygfox** [dwyl/best-evidence#7]
**As a**... user 
**I can**... provide written feedback about the app (and particularly the page I am currently on)
**So that**... the app can be improved and new or different features implemented.

- [x] A banner displays at the top of the app (on all pages) with the option to give feedback, similar to:
![image](https://user-images.githubusercontent.com/6057298/28272408-4f86a5a0-6b03-11e7-86af-6c656c6cca59.png)

- [x] By clicking on the link in the banner, the user's emails are opened with a blank email to this address
- [x] Small spike of 30 mins to investigate page tracking for feedback page origins

**Comment by Cleop** [comment]
@ajburls - what is the correct email that feedback emails should be sent to?

**Comment by Cleop** [comment]
Current banner wording/color: 
<img src="https://user-images.githubusercontent.com/16775804/28518996-e2f10ade-7061-11e7-9d47-98e69612364b.png" width=200px />

**Comment by ajburls** [comment]
@Cleop

**Comment by Cleop** [comment]
@ajburls - I've now updated the email address to the one you've provided so this is now ready to test again and if you're happy it can be closed.

**Comment by ajburls** [comment]
@cleop I tested this and sent a message to myself which duly arrived. One of the reasons for having feedback option on every page was so that we could tell which page feedback came from. Currently you can't do this. The feedback email is a blank email. It would be helpful if it could have something like 

_Feedback on BestEvidence App (page X)_

In subject line

**Comment by SimonLab** [comment]
At the moment the feedback linked can be clicked on the following urls:
- / 
- /session/new
- /consent
- /user/new
- /search

@ajburls I think we can predefine the body of the email with this information, would this be ok?
Also we have now Google Analytics tracking the click events on the feedback link and the information about the page is also saved this way

**Comment by ajburls** [comment]
@SimonLab Yes, I think that would give us enough information to know where it came from. Presumably it will activated on all pages in due course?

**Comment by SimonLab** [comment]
@ajburls This is now ready to be tested. The subject of the emails will contain the path of the page when the user click on the feedback link

**Comment by ajburls** [comment]
This works well on pages tested so far.
