### ISSUE TITLE
Problem with passwords

### ISSUE THREAD

**Issue by ajburls** [dwyl/best-evidence#70]
A few days ago I was unable to enter best-evidence-staging.herokuapp.com website with my city university email address and assumed it was because I had forgotten my password. Since there is nothing for forgotten password I simply opened another account with my personal email address. This is not working saying password name combination is invalid but I know I am using the correct password and have checked capital lock is not on.

![image](https://user-images.githubusercontent.com/30235568/28524395-3609c826-7078-11e7-8679-f1845147e4ea.png)

**Comment by ajburls** [comment]
@cleop - tried to check this but can't get to search page, see issue #70 just raised.

**Comment by ajburls** [comment]
@SimonLab @Cleop Just played around with this and it turns out that the email address is case sensitive. this needs to be changed but it does mean I can now get in to app to check pages.

**Comment by SimonLab** [comment]
Sorry @ajburls I just read your previous message and I've already reset your emails. You should be able to create them again and I will make sure the email are not case sensitive

**Comment by ajburls** [comment]
@SimonLab Thanks for heads up. I have re-registered, no problem. (I noticed capitalisation problem not yet fixed.)

**Comment by SimonLab** [comment]
The code for the capitalisation is currently in review (see the pull request #73 ) but this should be deployed soon today once it is approved

**Comment by SimonLab** [comment]
@ajburls this is now deployed to staging and ready to be tested

**Comment by ajburls** [comment]
OK - this problem seems to be resolved.
