### ISSUE TITLE
Search History UI

### ISSUE THREAD

**Issue by Cleop** [dwyl/best-evidence#71]
UI for 'History' page without bottom bar:
  - [x] Dates from database
  - [x] Notes symbol - notepad with pencil
  - [x] Notes toggle feature (note been made = squiggly line through it)
  - [x] Put Publications in a block displayed div so that when there is a one line short title it doesn't try to put two on one line
  - [x] Add L shaped line between symbols
  - [x] Make publications black font color

Review All link to not be included for now
Page scrolls infinitely

<img src="https://user-images.githubusercontent.com/16775804/28273692-e85a5c60-6b06-11e7-82ed-bbd2366a81e0.png" width=250px />

**Comment by ajburls** [comment]
When this was discussed with Harry the notes icon was going to be beside each resource used and coded in some way to show where there were notes and where notes had not yet been written. I am not sure how notes at the bottom would enable one to make notes that relate to a particular resource.

**Comment by markwilliamfirth** [comment]
Note for design of this page: according to #62 with regards to the history link:

>I think that we just want a link to history and no flag or numbers

**Comment by ajburls** [comment]
@markwilliamfirth this is right

**Comment by ajburls** [comment]
@Cleop 
Had a look at the notes page - looking good, Note that warning text needs improving - suggest change to (#65)

Do NOT to write notes that could could breach patient confidentiality

**Comment by markwilliamfirth** [comment]
@ajburls not sure what you mean with your reference to 65?

Please can you test and close this issue if you are happy?

**Comment by ajburls** [comment]
@markwilliamfirth  

I meant #97

**Comment by markwilliamfirth** [comment]
@ajburls if you're happy with the rest of the functionality and 97 is the only issue then this one can be closed and 97 be left open
