### ISSUE TITLE
add type of evidence to results

### ISSUE THREAD

**Issue by SimonLab** [dwyl/best-evidence#75]
As a developer I want a way to quickly know the type of evidence of a link so that I can style easily the result (colour + evidence pyramid).

- [x] map id of category returns by the API to the list of evidence types
- [x] create a new property that no the result object to store the evidence type

**Comment by SimonLab** [comment]
evidence must map the following categories:
11 - Systematic Reviews
1 - Evidence-based synposes
16 - Aus & NZ Guidelines
18 - Canada Guidelines
10 - UK Guidelines
9 - USA Guidelines
4 - Other Guidelines
34 - Regulatory Guidance
13 - Key Primary Research
2 - Clinical Q&A
27 - Controlled Trials
14 - Primary Research
35 - Ongoing Systematic Reviews
30 - Ongoing Clinical Trials
22 - Patient Decision Aids
8 - Patient Information Leaflets
29 - Blogs
5 - eTextbooks

**Comment by SimonLab** [comment]
This is ready to be tested @ajburls 
![image](https://user-images.githubusercontent.com/6057298/28631105-0915e086-7224-11e7-9e87-0c8470d214b6.png)

**Comment by ajburls** [comment]
@SimonLab Working well on search. Looks good

Not sure if I should close this issue or whether it is still part of issue about being able to select a level of evidence to review.

**Comment by SimonLab** [comment]
I think this issue could be close. We have the following issue #25 where we will add the filters to the results page
