### ISSUE TITLE
Attempting to register existing email address

### ISSUE THREAD

**Issue by ajburls** [dwyl/best-evidence#77]
When I was testing whether the email address capitalisation issue was satisfactorily resolved, I tried to create an account with different capitalisation for an account that existed. I told me the account existed but stayed on the page for creating a new account. I think it would be better in such circumstances to return to the previous login page.

**Comment by SimonLab** [comment]
Just to recap and to be sure I understand correctly, when a user attempt to create an account with an existing email address we want that user to be redirected to the login page, it this right?

**Comment by ajburls** [comment]
@SimonLab yes, there seems to be no point returning them to the create an account page.

**Comment by ajburls** [comment]
This is working and returning people to login page. I think it needs a message as a bit disorienting but I will close this and add as a low priority issue.
