### ISSUE TITLE
Search button

### ISSUE THREAD

**Issue by ajburls** [dwyl/best-evidence#94]
As a user of the mobile version of the app
I need a search button near the search box
So I can search immediately after a voice to text search without having to go back to the keyboard.

**Comment by markwilliamfirth** [comment]
@Cleop please can you add a time estimate to this?

**Comment by ajburls** [comment]
(Similar to agreed "search" button on history page where currently says done #85)

**Comment by ajburls** [comment]
@Cleop This is looking good on both phones. Thanks
