### ISSUE TITLE
Year needed on date of search in history

### ISSUE THREAD

**Issue by ajburls** [dwyl/best-evidence#95]
As a user
I need to know the year of a search too,
so that I can prepare my CPD returns and remember when a search was done.

**Comment by markwilliamfirth** [comment]
@ajburls please could you assign a priority label to this issue?

**Comment by markwilliamfirth** [comment]
@ajburls please can you test and close this issue if you are happy?

**Comment by ajburls** [comment]
@markwilliamfirth looks good. Thanks
