### ISSUE TITLE
Alter Wording for Breach of Patient Confidentiality Warning

### ISSUE THREAD

**Issue by ajburls** [dwyl/best-evidence#97]
As a clinician user of the app
I need to be reminded not to breach patient confidentiality when I write notes

Current wording
![image](https://user-images.githubusercontent.com/30235568/28670550-27e29790-72d1-11e7-922b-a1d22e9535e0.png)

 needs to be improved. Suggest changing to

_Do NOT to write notes that could could breach patient confidentiality_

I like the warning triangle

- [x] Change wording
- [x] Swap for triangular asset
- [x] Move above the notes field

**Comment by markwilliamfirth** [comment]
@ajburls please could you assign a priority label to this issue?

**Comment by Cleop** [comment]
Outstanding asset for triangular ! icon, will chase @harrygfox

**Comment by markwilliamfirth** [comment]
@Cleop temporary low quality version:

![temp](https://user-images.githubusercontent.com/5732209/29955191-a510fa5a-8ee6-11e7-8981-ccc4e5fe78ff.png)

**Comment by ajburls** [comment]
Not sure state/meaning of last few comments but did notice last image not triangle. This is shape wanted although this is image not an icon but it shows what i meant Warning sign https://g.co/kgs/v3Fwa8

**Comment by markwilliamfirth** [comment]
![warning-pink](https://user-images.githubusercontent.com/5732209/29961025-5130ab5c-8efe-11e7-9c02-a4c8926defbb.png)
![warning](https://user-images.githubusercontent.com/5732209/29961026-514729cc-8efe-11e7-88f0-e26746496a68.png)

@ajburls do you mean like one of these? Do you have a preference for colour?

**Comment by ajburls** [comment]
I think keep it in same colour (red) as warning text to keep it unfussy

**Comment by Cleop** [comment]
<img src="https://user-images.githubusercontent.com/16775804/29961942-25e9bfb0-8ef9-11e7-8687-815c0d499051.png" width=260px />
An inverted color version.

**Comment by ajburls** [comment]
@Cleop This is a good point and what you have done looks good (I would put it in City red as @markwilliamfirth suggested for aesthetics. Also, it would be nice if we could get text onto a single line. Would "Do NOT breach patient confidentiality" be better?

**Comment by ajburls** [comment]
@Cleop This looks fine
