### ISSUE TITLE
Change functionality of Search Terms box on results page

### ISSUE THREAD

**Issue by ajburls** [dwyl/best-evidence#99]
As a user of this app
I need to have the search terms box on the results page link to a search

Even though I know that the search term box on the results page isn't a search box, I repeatedly find myself amending a search and trying to run it. This means that this is a systematic error cause by the design and I think it would probably be best to make this box editable and the search runable directly from this page (has added benefit of saving a click to run a search again). The alternatives would be: just to remove the description of the search; not put the search terms in a box so that less likely to give misleading subliminal messages; prevent the box being clickonable and editable.

**Comment by markwilliamfirth** [comment]
@ajburls as far as I understand this functions correctly - I am able to run a search from the search terms box on the results page - please could you test if this works on your end?

**Comment by ajburls** [comment]
I can't get into app just now



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by markwilliamfirth** [comment]
@ajburls seems to be working for me now:

<img width="1258" alt="screen shot 2017-08-04 at 17 22 57" src="https://user-images.githubusercontent.com/5732209/28977382-b198cc20-7939-11e7-87fa-77770402750a.png">

Is it working correctly now? If not, can you describe the steps that need to be taken to reproduce the issue?

**Comment by ajburls** [comment]
No - still won't let me log in as ajburls@yahoo.co.uk from Samsung nor register an account with this email address.. "start searching" button just returns me to login screen and 

I had to invent fake email address and register again. Then it would let me search. However, when app closed and re-opened, it wanted me to login again rather than going straight to app and it won't let me log in with that fake address (rubbish5) or my email address.

However on the laptop it does accept my email address and password and also remembers me if I have closed the app.

**Comment by markwilliamfirth** [comment]
@SimonLab to look into this bug

**Comment by markwilliamfirth** [comment]
@ajburls Simon has deleted your yahoo email from the database, so please try signing up again

**Comment by ajburls** [comment]
@markwilliamfirth Mark, not sure what exactly the please test refers to. If it is accessing the app from my phone, no I still can't do this without generating yet another fake ID. 

I have tested results page search box and it appears unchanged (the screenshot you included above is not the page I am referencing) - you can edit and run search from results page but the "done" button is still appearing where I would expect it to say search or run. I think this may be in another issue because I remember someone saying they understood what I meant and would relocate return to search screen button.

**Comment by ajburls** [comment]
@markwilliamfirth @SimonLab I created a new account. I was able to log in with it but when I closed the app I was required to login again.

So progress in that I can get into app without creating a new fictitious account but still not doing what it was doing before and what is required - allowing a user who has logged in on a new device to use the app again without further requirement for loggin in.

**Comment by markwilliamfirth** [comment]
Linked to #88

**Comment by markwilliamfirth** [comment]
Thanks @ajburls glad that you can log in now with the yahoo email, I've noted above with the login tracking issue that you had to log in more than once.

With regards to the main issue description - the ability to run a search from the results page - are you able to do this now in your testing?

With regards to your comment about the wording - that is recorded in a separate issue here: https://github.com/dwyl/best-evidence/issues/85

**Comment by ajburls** [comment]
@markwilliamfirth _With regards to the main issue description - the ability to run a search from the results page - are you able to do this now in your testing?_ Yes

Is this _I've noted above with the login tracking issue that you had to log in more than once._ Part of this issue or should it now be closed?

**Comment by markwilliamfirth** [comment]
@ajburls because I've made a reference to issue 88 above, it means it's linked that issue to this one so it's recorded against the login tracking issue. Issue 85 is taking care of the search and return buttons so since you've confirmed the functionality is working this issue can be closed now 😄 👍
